name: deploy-github-page

#on:
#  push:
#    branches:
#      - master

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: generate static file
        run: |
          cd docs
          npx gitbook-cli install
          npx gitbook-cli build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/_book
          personal_token: {{ GH_PAGES_TOKEN }}
