name: docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: generate static file
        run: |
          cd docs
          npx gitbook-cli install
          npx gitbook-cli build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/_book
          force_orphan: true
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
