name: docs

on:
  push:
    branches:
      - master
      - doc-rebuild

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use node v12
        uses: actions/setup-node@v1
        with:
          node-version: '10.21.0'

      - name: generate static file
        run: |
          cd docs
          npx gitbook-cli install
          npx gitbook-cli build

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/_book
          force_orphan: true
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Deploy to self-host server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DOCS_SERVER_HOST }}
          username: ${{ secrets.DOCS_SERVER_USER }}
          key: ${{ secrets.DOCS_SERVER_KEY }}
          source: "./docs/_book"
          target: "${{ secrets.DOCS_SERVER_DIR }}"
